# Generated by Django 5.1 on 2024-09-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozayede', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.IntegerField(blank=True, default=models.IntegerField(default=0), null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_price',
            field=models.IntegerField(default=0),
        ),
    ]
